.level = INFO
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
# This is the worst formatting system I've ever had to experience.
java.util.logging.SimpleFormatter.format = [%1$tb %1$td %1$tT %1$tZ] [%4$s] %5$s %n
