.level = INFO
io.vertx.ext.web.level = FINEST
io.vertx.level = INFO
com.hazelcast.level = INFO
io.netty.util.internal.PlatformDependent.level = SEVERE
java.util.logging.ConsoleHandler.level = INFO

handlers = java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
# This is the worst formatting system I've ever had to experience.
java.util.logging.SimpleFormatter.format = [%1$tb %1$td %1$tT %1$tZ] [%4$s] %5$s %6$s %n
